identify_news_outlets_task:
  description: >
    Identify the top and most reputable news outlets that cover the topic of interest. Topic: {topic}.
    Use Google to identify the most recent URLs of these news outlets that cover the topic.
  expected_output: > 
    At least 3 news outlets or resources that are known for covering the topic. 
    You will return the URLs of these outlets.
  agent: topic_expert

search_specialized_sources_task:
  description: >
    Using the URLs of the identified news outlets, navigate to these outlets to search for the most recent 
    news articles related to the following topic: {topic}. 
    Provide a list of the most relevant and recent news articles. You will search from
    at least 2 different specialized sources. Make sure to search for recent news articles. Current date: {current_date}.
  expected_output: >
    A list of {num_starting_pool_news} news articles from the specialized sources about {topic}, each with 
    a title, very brief summary, and the website url.
  agent: topic_expert

general_web_search_task:
  description: >
    Identify top news about {topic} by searching the web via Google and provide a list of 
    the most relevant and recent news articles. Make sure to search for recent news articles. Current date: {current_date}.
  expected_output: >
    A list of {num_starting_pool_news} news articles from specialized sources about {topic}, each with 
    a title, very brief summary, and the website url.
  agent: research_analyst

prioritize_news_task:
  description: >
    Prioritize the news articles found by the team based on relevance and alignment
    to the user's preferences, including the user's desired perspective. If there are
    duplicate news with different perspectives, choose the best source.
    User perspective: {perspective}.
  expected_output: >
    A list of {num_max_news} news articles from specialized sources about {topic}, each with 
    a title, a very brief summary, the selected best url for the source, and the unmodified original content of the article. 
    The result must conform to a pydatic model of NewsList type.
  agent: topic_expert