scrape_news_task:
  description: >
    Scrape the news from the given URLs, and provide the content and summary of the news.
    URLs: {urls}
    You will strictly scrape the news from the given URLs.
  expected_output: > 
    The news title, summary, source url, topic, and content of the news.
    You will return the content and summary of the news in a pydantic model of NewsList type.
    Even if you are given a single URL, you will return a list of news objects (typed as NewsWithSources).
    Format the output as a JSON object conforming to the following structure:
    {
      "news_list": [
        {
          "news_title": "...",
          "summary": "...",
          "source_url": "...",
          "topic": "...",
          "content": "..."
        }
      ]
    }
  agent: news_scraper